#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

TAG_BASE= $(echo $DOCKER_TAG | sed -e "s/\.amd64$//g" | sed -e "s/\.arm32v5$//g" | sed -e "s/\.arm32v7$//g" | sed -e "s/\.arm64v8$//g" | sed -e "s/\.arm64$//g"  )

sed -i "s|{IMAGE_NAME}|$IMAGE_NAME|g" multi-arch-manifest.yaml
sed -i "s|{TAG_BASE}|$TAG_BASE|g" multi-arch-manifest.yaml
  
./manifest-tool push from-spec multi-arch-manifest.yaml
